# Constants
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "aMaze"

TILE_SCALE = 0.5

PLAYER_SCALE = 0.9

# Movement speed of player, in pixels per frame
PLAYER_MOVEMENT_SPEED = 5
ENEMY_MOVEMENT_SPEED = 5

MAX_INVINCIBILITY_TIMER = 5

BULLET_SCALE = 0.45

SHORT_DISTANCE_MIN = 250
SHOOTING_DISTANCE_MIN = 300
SHOOTING_DISTANCE_MAX = 320

ENEMY_MOVEMENT_SPEED = 5

